mate-desktop/mate-power-manager

- man/Makefile.am
- man/mate-power-backlight-helper.sgml
- man/mate-power-manager-bugreport.sgml
taken from Debian patch:
http://anonscm.debian.org/cgit/pkg-mate/mate-power-manager.git/commit/?id=324a45a723c377765337900667ea385cbedddb8c
fixes https://github.com/mate-desktop/mate-power-manager/issues/56
also fixes https://github.com/mate-desktop/mate-power-manager/issues/102
> add missing manpages

- src/gpm-control.c
We should catch and free the GVariant returned by proxy calls even if
the DBus method returns no value.
> Fix memory leak problem when calling logind DBus method

- src/gpm-prefs-core.c
By adding GPM_ACTION_POLICY_NOTHING to the available power button
actions, it is now possible for MATE users to disable the system's
power button, while being in a MATE desktop session.
This is helpful if a system's power button is designed in a way that it
can easily be accidentally hit by the user without noticing.
> Support disabling of PowerBtn.

- applets/brightness/brightness-applet.c
This fixes the background for GTK+ 3 themes which don't support mate-panel explicitly. Themes could still overwrite the background if they want in the usual way.
> bightness: Don't remove slider background

- src/gpm-tray-icon.c
- src/msd-osd-window.c
This is a fix for https://github.com/mate-desktop/mate-power-manager/issues/188
with Gtk+-3.21.2.
And build warning fix.
@lukefromdc @monsta 
Please test
> port gtk_style_context and other fixes

- applets/brightness/brightness-applet.c
- src/gpm-backlight.c
- src/gpm-button.c
- src/gpm-kbd-backlight.c
- src/gsd-media-keys-window.c
- src/msd-osd-window.c
- src/msd-osd-window.h
- fixes some deprecations
- sync OSD code with m-s-d
- in result one dep to libmate-desktop is droped
- only 3 deps to libmate-desktop/mate-aboutdialog.h are left
@monsta @lukefromdc @dnk 
Plaese test
> prepare gtk3 migration

- src/msd-osd-window.c
Brightness: fix OSD rendering when not composited
Also add style class msd-osd-window-solid, same as mate-settings-daemon volume control.
Based on
https://github.com/mate-desktop/mate-settings-daemon/commit/5d580b9985b61a486c8d23eaa34091a14d01b9e0
and
https://github.com/mate-desktop/mate-settings-daemon/commit/9aa4c4e379e71ebe8436898a3af61c4c96c9cc8a
> Brightness: fix OSD rendering when not composited

- src/gpm-brightness.c
Added checking the "Backlight" property. "BACKLIGHT" appears to be the legacy property.
This resolves an issue where xbacklight can change the backlight, but mate-power-manager can't.
> Check both the "Backlight" and "BACKLIGHT" xrandr properties.

- src/egg-console-kit.c
- src/egg-console-kit.h
- src/gpm-control.c
- src/gpm-prefs-core.c
Same as #209, with corrections. Now when we want to know if suspend/hibernate is allowed, we ask ConsoleKit2, not upower. This correction was needed because upower 0.99 doesn't even have the necessary properties to answer that question. :slightly_smiling_face: 
@willysr @ryanpcmcquen @joakim-tjernlund @NP-Hardass @obache
Please test it (and post your upower version just in case).
Note that it should **not** be tested with logout/shutdown dialog - that's in ```mate-session-manager```.
Instead, you need to run ```mate-power-preferences``` and assign Suspend or Hibernate action to power button (or to suspend button - not sure if any system has it). Then test it using that button.
> Replace deprecated UPower functions with ConsoleKit2 equivalents, with corrections

- applets/brightness/gpm-common.c
- applets/inhibit/gpm-common.c
- src/gpm-common.c
- src/gpm-manager.c
Please test.
Note for testing the help links from applets you need to edit this line
https://github.com/mate-desktop/mate-power-manager/blob/master/applets/brightness/brightness-applet.c#L856
because of this yelp issue https://bugzilla.gnome.org/show_bug.cgi?id=778553
Use
```
gpm_applet_help_cb (GtkAction *action, gpointer data)
{
gpm_help_display ("applets-brightness");
}
```
and the link will open fine.
And do similar for inhibit-applet.
> don't use deprecated gtk_show_uri

- src/msd-osd-window.c
This commit reverts:
https://github.com/mate-desktop/mate-power-manager/commit/f748d5794f02d02ba949ad1503ed72207efca40c
And it applies an alternative to fix the deprecated functions:
gdk_screen_get_width
gdk_screen_get_height
> WidthOfScreen and HeightOfScreen implementation

- applets/inhibit/inhibit-applet.c
Stop failure to redraw on system panel background by using a GtkImage to render the icon
Fix https://github.com/mate-desktop/mate-power-manager/issues/238
> inhibit applet: fix rendering of icon

- applets/brightness/gpm-common.c
- applets/inhibit/gpm-common.c
- configure.ac
- src/gpm-backlight.c
- src/gpm-common.c
- src/gpm-kbd-backlight.c
- src/gpm-manager.c
- src/msd-osd-window.c
and drop additional checks for min/max GLib versions, it's not needed
> require GTK+ 3.22 and GLib 2.50

- applets/inhibit/inhibit-applet.c
Fix https://github.com/mate-desktop/mate-power-manager/issues/248
Note that this partially reverts https://github.com/mate-desktop/mate-power-manager/commit/6ecb73c1a876e48d2d2ef05603087bd83ac7022f by returning to the previous cairo rendering of the icon, but only of the icon.
The code for backgrounds behind the icons was not restored, as all backgrounds render fine without it so long as the applet is hidden and reshown on each change of icon. This must be done ONLY when the icon is changed, not everytime the draw callback runs.
The use of the GtkImage required use of gtk_widget_show in a callback that seems to run constantly, thus causing excess CPU use
> Inhibit Applet: Fix excessive CPU use

- applets/inhibit/inhibit-applet.c
Restore icon scaling to match panel size without bringing back high CPU use. Note that GNOME's behavior of matching icon size makes it easier to get sharp rendering of png icons. Tests with hidpi (window-scaling=2) looked good. In this case GTK itself is still handling all icon rendering.
> inhibit: always scale icon to match panel size

- src/Makefile.am
This comes from the patch attached to https://bugs.debian.org/912842. I think the patch can be upstreamed.
Currently m-p-m is our only project that uses an external libtool binary (which is in `libtool-bin` package in Debian). This PR switches it to local, generated `./libtool`.
How to test:
- launch the build
- check that `./libtool` is generated
- check that `src/org.mate.PowerManager.*.h` header files are still properly generated from `src/org.mate.PowerManager.xxx.xml` ones
> use libtool generated during build instead of external one

- help/C/index.docbook
- help/C/legal.xml
The info is already present in footer.
> Help: Remove About section

- NEWS
- README
- applets/brightness/brightness-applet.c
- applets/inhibit/inhibit-applet.c
- configure.ac
- help/C/index.docbook
- policy/org.mate.power.policy.in2
- src/gpm-tray-icon.c
Now the official web site is https://mate-desktop.org/.
> Change url project's website

- .travis.yml
- Makefile.am
debian buster doesn't have the package `libgnome-keyring-dev` (is deprecated)
not sure how to fix this in travis, in debian it was fixed with:
https://salsa.debian.org/debian-mate-team/mate-power-manager/commit/8158d27caff9917c04d5e9f3c05f76cbf98430ae
https://salsa.debian.org/debian-mate-team/mate-power-manager/commit/d968620c262a378a45d65ad65cb6979670fc1238
debian bug related:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867937
> [1.20 branch] travis: use Debian Buster which has 1.20

- .travis.yml
seems the package `libgnome-keyring-dev` was removed in `ubuntu 19.10`
> [ci] remove libgnome-keyring-dev on ubuntu

- src/gpm-upower.c
gpm-upower: fix -Wlogical-not-parentheses warning
```
gpm-upower.c:222:51: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
gpm-upower.c:222:44: note: add parentheses around left hand side expression to silence this warning
222 |   if (state == UP_DEVICE_STATE_CHARGING || !state == UP_DEVICE_STATE_DISCHARGING) {
|                                            ^~~~~~
```
> gpm-upower: build warnings

- data/gpm-prefs.ui
This fixes navigation with mnemonic keys as well as giving proper a11y context for the labeled widgets.
Fixes #292.
> prefs: Fix mnemonic relationships

- configure.ac
- src/gpm-backlight.c
- src/gpm-button.c
- src/gpm-engine.c
- src/gpm-kbd-backlight.c
- src/gpm-manager.c
- src/gpm-prefs-core.c
- src/gpm-statistics.c
Use up_client_get_devices2()
The previous code would have leaked all the UpDevice objects because no
free function was set on the returned GPtrArray.
With depending on upower-glib 0.99.8 get_devices() was deprecated and get_devices2() was introduced, we can simply switch to get_devices2() which does set a free function on
the returned GPtrArray, stopping the leak.
Inspired from:
https://gitlab.gnome.org/GNOME/gnome-control-center/commit/c1210c5
see upower upstream:
https://gitlab.freedesktop.org/upower/upower/commit/cb1071b
Please review.
> upower deprecations

- .travis.yml
- applets/brightness/Makefile.am
- applets/inhibit/Makefile.am
- configure.ac
- src/Makefile.am
MATE_COMPILE_WARNINGS is present in configure.ac but WARN_CFLAGS
variable is not used. git grep WARN_CFLAGS
It removes -enable-extra-warn=yes, since it is recommended to use
-enable-compile-warnings=maximum.
It sets -enable-compiler-warnings=yes, the default value for all
MATE packager for now.
It prints WARN_CFLAGS in summary table.
> Use WARN_CFLAGS which are only set with --enable-compiler-warnings

- configure.ac
-enable-debug=yes/info/profile/no
By default, compiler debug flags are disabled.
Test 1
```
$ ./autogen.sh --prefix=/usr -enable-debug
...
MATE Power Manager 1.23.0
=============================
prefix:                    /usr
datadir:                   ${datarootdir}
compiler:                  gcc
cflags:                     -g -O0
gnome-keyring support:     yes
Building extra applets:    yes
Self test support:         no
dbus-1 services dir:       ${datarootdir}/dbus-1/services
Now type `make' to compile mate-power-manager
```
Test 2
```
$ ./autogen.sh --prefix=/usr
...
MATE Power Manager 1.23.0
=============================
prefix:                    /usr
datadir:                   ${datarootdir}
compiler:                  gcc
cflags:
gnome-keyring support:     yes
Building extra …
```
> Set compiler debug flags using MATE_DEBUG_CHECK

- applets/brightness/brightness-applet.c
Please review.
During testing master branch i noticed that the slider-window isn't accessible from panel with keyboard navigation. So this isn't related to PR.
> brightness-applet: use GdkSeat operations

- applets/brightness/brightness-applet.c
- applets/inhibit/inhibit-applet.c
Fixes the warnings:
```
brightness-applet.c:81:37: warning: redundant redeclaration of 'gpm_brightness_applet_init' [-Wredundant-decls]
brightness-applet.c:81:37: warning: redundant redeclaration of 'gpm_brightness_applet_class_init' [-Wredundant-decls]
inhibit-applet.c:75:34: warning: redundant redeclaration of 'gpm_inhibit_applet_init' [-Wredundant-decls]
inhibit-applet.c:75:34: warning: redundant redeclaration of 'gpm_inhibit_applet_class_init' [-Wredundant-decls]
```
> avoid redundant redeclarations

- applets/brightness/brightness-applet.c
- applets/inhibit/inhibit-applet.c
- src/gpm-engine.c
- src/gpm-manager.c
- src/gpm-prefs.c
- src/gpm-statistics.c
```
gpm-manager.c:952:7: warning: unused variable ‘timeout’ [-Wunused-variable]
952 |  gint timeout;
|       ^~~~~~~
gpm-engine.c:800:8: warning: unused variable ‘i’ [-Wunused-variable]
800 |  guint i;
|        ^
gpm-engine.c:799:13: warning: unused variable ‘array’ [-Wunused-variable]
799 |  GPtrArray *array = NULL;
|             ^~~~~
gpm-prefs.c:70:11: warning: unused variable ‘ret’ [-Wunused-variable]
70 |  gboolean ret;
|           ^~~
gpm-statistics.c:1212:15: warning: unused variable ‘text’ [-Wunused-variable]
1212 |  const gchar *text;
|               ^~~~
brightness-applet.c:979:19: warning: unused variable ‘connection’ [-Wunused-variable]
979 |  DBusGConnection *connection;
|                   ^~~~~~~~~~
inhibit-applet.c:461:19: warning: unused variable ‘connection’ …
```
> Remove warnings: unused variable

- src/gpm-backlight-helper.c
```
gpm-backlight-helper.c:43:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
43 | gcm_backlight_helper_get_best_backlight ()
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Remove warning function declaration isn’t a prototype

- src/gpm-backlight.c
#320 works fine, but it floods ~/.xsession-errors with:
```
(mate-power-manager:1589): PowerManager-WARNING **: 21:55:02.775: no dimming hardware
```
> gpm-backlight: silent "no dimming hardware" message unless debug

- src/gpm-statistics.c
Removed warnings:
```
gpm-statistics.c:507:2: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
507 |  GTimeVal timeval;
|  ^~~~~~~~
---
gpm-statistics.c:554:2: warning: ‘g_get_current_time’ is deprecated: Use 'g_get_real_time' instead [-Wdeprecated-declarations]
554 |  g_get_current_time (&timeval);
|  ^~~~~~~~~~~~~~~~~~
```
> Remove warning: ‘GTimeVal’ is deprecated

- src/gpm-phone.c
Needed to avoid spamming ~/.xsession-errors since https://github.com/mate-desktop/mate-power-manager/commit/33e52564affb7fbc50ad68a08c43c9f70e7d1bb4
Note, i don't think that gpm-phone code is used in general, because gnome-phone is needed. And this piece of software is EOL since a long time.
> gpm-phone: silent "not connected" message unless debug

- src/gpm-kbd-backlight.c
Automatically change keyboard back-light only when enabled on battery. Respect `org.mate.power-manager kbd-backlight-battery-reduce` settings.
Keep previous brightness level between state change.
Fixes https://ubuntu-mate.community/t/keyboard-light-keeps-turning-on-after-login-and-or-unlock/6914/24
Closes #253
> gpm-kbd-backlight: do not change keyboard back-light when disabled

- applets/brightness/brightness-applet.c
- src/egg-array-float.c
- src/gpm-manager.h
- src/gpm-tray-icon.c
- src/msd-osd-window.c
```
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/[[:space:]]*$//' {} \;
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/\t*$//' {} \;
```
> Remove trailing spaces/tabs

- .build.yml
- README
- configure.ac
- src/Makefile.am
- src/gpm-control.c
Adds libsecret support.  I'll leave it up to you guys to decide at a future time about dropping libgnome-keyring support.  This should close out Issue #239.
I wasn't able to runtime test the code in-situ, but copied it to a standalone file and it locked the databased as expected.
> Port to libsecret, #239

- .build.yml
`pangox.h` is not included in any file, nor can `pango_x_` be found in the current code.
https://gitlab.gnome.org/Archive/pangox-compat
> ci: remove pangox-compat-devel from fedora deps

- .build.yml
- src/gpm-prefs-core.c
Fix building 1.24 branch + update travic (CI) config.
> Fix building 1.24 branch

- src/gpm-backlight-helper.c
- src/gpm-main.c
- src/gpm-prefs.c
- src/gpm-statistics.c
```
gpm-main.c:175:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL}
^
--
gpm-prefs.c:74:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL}
^
--
gpm-statistics.c:1211:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL}
^
--
gpm-backlight-helper.c:174:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL}
^
```
> Fix build warnings about missing field initializer

- src/gpm-backlight.c
It removes the build warning below:
```
gpm-backlight.c:263:1: warning: unused function 'gpm_common_sum_scale' [-Wunused-function]
```
configure summary:
```
MATE Power Manager 1.26.0
=============================
prefix:                    /usr
datadir:                   ${datarootdir}
compiler:                  clang
cflags:                    -g -O0 -Wconversion -Wunused-macros -Wunused-parameter
cwarnings:                 -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wno-unused-parameter -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Werror=format-security
libsecret support:         yes
gnome-keyring support:     no
Building extra applets:    yes
Self test …
```
> gpm-backlight: unused function 'gpm_common_sum_scale'

- src/gsd-media-keys-window.c
- src/msd-osd-window.c
```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
gsd-media-keys-window.c:178:46: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
window->priv->volume_muted = muted;
~ ^~~~~
--
msd-osd-window.c:444:39: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
window->priv->is_composited = gdk_screen_is_composited (screen);
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Fix implicit conversion changes signedness: 'gboolean' to 'guint'

- applets/brightness/brightness-applet.c
- applets/inhibit/inhibit-applet.c
Test:
```
CFLAGS="-Werror=missing-prototypes" ./autogen.sh --prefix=/usr && make && sudo make install
```
Warnings
```
mate-power-manager.make.log:brightness-applet.c:910:1: warning: no previous prototype for function 'gpm_brightness_applet_dbus_connect' [-Wmissing-prototypes]
mate-power-manager.make.log:brightness-applet.c:954:1: warning: no previous prototype for function 'gpm_brightness_applet_dbus_disconnect' [-Wmissing-prototypes]
mate-power-manager.make.log:brightness-applet.c:982:1: warning: no previous prototype for function 'gpm_brightness_applet_name_vanished_cb' [-Wmissing-prototypes]
mate-power-manager.make.log:inhibit-applet.c:362:1: warning: no previous prototype for function 'gpm_inhibit_applet_dbus_connect' [-Wmissing-prototypes] …
```
> Fix -Wmissing-prototypes warnings

- applets/brightness/org.mate.BrightnessApplet.mate-panel-applet.desktop.in.in
- applets/inhibit/org.mate.InhibitApplet.mate-panel-applet.desktop.in.in
*Brightness applet depends on Xrandr, and wlr-randr wayland equivalent does not yet offer brightness control
*Inhibit applet depends on Xevent and on x11 extension DPMS (X Display Power Management Signaling)
> Brightness, Inhibit: mark both applets incompatable with wayland

- src/gpm-kbd-backlight.c
See commit log, but most important bits:
* [**Fix toggling backlight back on**](https://github.com/mate-desktop/mate-power-manager/commit/1def59bb169006897048b8de351e1ddd1bba4441).  When triggering the toggle action, without this it turns off just fine, but never comes back: one has to use the up action enough times to get back the previous brightness.  This was a simple one.
* [**Persistently save user-set brightness**](https://github.com/mate-desktop/mate-power-manager/commit/4d725c390cd5f7f19d2aea8c7cddf88c89b51cc4).  Currently the brightness was never saved, so one would have had to manually change the "brightness on AC" value to restore a desired value.  This seems overly annoying when having up/down/toggle keyboard buttons that the values they set is not remembered.  So, I changed …
> Keyboard backlight handling improvements
